# Generated by Django 5.1.1 on 2024-09-12 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("latitude", models.CharField(blank=True, max_length=200, null=True)),
                ("longitude", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Organizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("version", models.CharField(max_length=4)),
                (
                    "uid",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=3)),
                ("description", models.TextField()),
                ("image_url", models.URLField()),
                ("web_sale", models.URLField(blank=True, null=True)),
                ("source_web_promote", models.URLField(blank=True, null=True)),
                ("comment", models.CharField(blank=True, max_length=200)),
                ("edit_modify_date", models.DateTimeField()),
                ("source_web_name", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("hit_rate", models.IntegerField(default=0)),
                ("show_unit", models.CharField(max_length=300)),
                ("discount_info", models.TextField(blank=True, null=True)),
                ("description_filter_html", models.TextField(blank=True, null=True)),
                (
                    "master_unit",
                    models.ManyToManyField(
                        related_name="master_events", to="DataGovCRUD.organizer"
                    ),
                ),
                (
                    "other_unit",
                    models.ManyToManyField(
                        related_name="other_events", to="DataGovCRUD.organizer"
                    ),
                ),
                (
                    "sub_unit",
                    models.ManyToManyField(
                        related_name="sub_events", to="DataGovCRUD.organizer"
                    ),
                ),
                (
                    "support_unit",
                    models.ManyToManyField(
                        related_name="support_events", to="DataGovCRUD.organizer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShowInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("on_sale", models.BooleanField()),
                ("price", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataGovCRUD.event",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataGovCRUD.location",
                    ),
                ),
            ],
        ),
    ]
