# Generated by Django 5.1.1 on 2024-09-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataGovCRUD", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showinfo",
            name="time",
            field=models.DateField(),
        ),
    ]
