# Generated by Django 5.1.1 on 2024-09-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataGovCRUD", "0002_alter_showinfo_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="edit_modify_date",
            field=models.DateTimeField(null=True),
        ),
    ]
