# Generated by Django 5.1.1 on 2024-09-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataGovCRUD", "0003_alter_event_edit_modify_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="uid",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
