# Generated by Django 5.1.1 on 2024-09-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataGovCRUD", "0004_alter_event_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="uid",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
