# Generated by Django 5.1.1 on 2024-09-14 16:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("DataGovCRUD", "0006_alter_event_hit_rate_alter_event_uid"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("name", "address")},
        ),
    ]
